DROP TABLE IF EXISTS pessoas;
CREATE TABLE pessoas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255)
);

DROP TABLE IF EXISTS carros;
CREATE TABLE carros (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255),
    preco DECIMAL(10, 2),
    peso DOUBLE
);